env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  jquery: true
  node: true
extends: 
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - off
  no-empty:
    - off
  camelcase:
    - error
    - properties: always
  no-var:
    - error
  require-atomic-updates:
    - warn
  no-console:
    - error
